"""Parsing utilities for dacpac/bacpac content."""

from parsing.context import ParsingContext, scan_elements
from parsing.extractors import (
    SqlCheckConstraintExtractor,
    SqlColumnStoreIndexExtractor,
    SqlDatabaseOptionsExtractor,
    SqlDefaultConstraintExtractor,
    SqlExtendedPropertyExtractor,
    SqlFilegroupExtractor,
    SqlForeignKeyConstraintExtractor,
    SqlIndexExtractor,
    SqlInlineTableValuedFunctionExtractor,
    SqlPartitionFunctionExtractor,
    SqlPartitionSchemeExtractor,
    SqlPermissionStatementExtractor,
    SqlPrimaryKeyConstraintExtractor,
    SqlProcedureExtractor,
    SqlRoleExtractor,
    SqlScalarFunctionExtractor,
    SqlSchemaExtractor,
    SqlSequenceExtractor,
    SqlTableExtractor,
    SqlTableTypeExtractor,
    SqlUniqueConstraintExtractor,
    SqlViewExtractor,
    extract_columns,
    extract_compression_options,
    extract_computed_column,
    extract_function_body,
    extract_indexed_columns,
    extract_parameters,
    extract_primary_key,
    extract_simple_column,
    register_spec05_extractors,
    register_spec06_extractors,
    register_spec07_extractors,
    register_spec08_extractors,
    register_spec09_extractors,
)
from parsing.metadata_parser import XmlMetadataParser
from parsing.model_parser import XmlModelParser
from parsing.name_parser import parse_name
from parsing.registry import ExtractorRegistry
from parsing.xml_helpers import (
    CdataResult,
    extract_type_specifier,
    get_cdata_property,
    get_relationship_inline_elements,
    get_relationship_references,
    get_simple_property,
)

__all__ = [
    "CdataResult",
    "ExtractorRegistry",
    "ParsingContext",
    "SqlCheckConstraintExtractor",
    "SqlColumnStoreIndexExtractor",
    "SqlDatabaseOptionsExtractor",
    "SqlDefaultConstraintExtractor",
    "SqlExtendedPropertyExtractor",
    "SqlFilegroupExtractor",
    "SqlForeignKeyConstraintExtractor",
    "SqlIndexExtractor",
    "SqlInlineTableValuedFunctionExtractor",
    "SqlPartitionFunctionExtractor",
    "SqlPartitionSchemeExtractor",
    "SqlPermissionStatementExtractor",
    "SqlPrimaryKeyConstraintExtractor",
    "SqlProcedureExtractor",
    "SqlRoleExtractor",
    "SqlScalarFunctionExtractor",
    "SqlSchemaExtractor",
    "SqlSequenceExtractor",
    "SqlTableExtractor",
    "SqlTableTypeExtractor",
    "SqlUniqueConstraintExtractor",
    "SqlViewExtractor",
    "XmlMetadataParser",
    "XmlModelParser",
    "extract_columns",
    "extract_compression_options",
    "extract_computed_column",
    "extract_function_body",
    "extract_indexed_columns",
    "extract_parameters",
    "extract_primary_key",
    "extract_simple_column",
    "extract_type_specifier",
    "get_cdata_property",
    "get_relationship_inline_elements",
    "get_relationship_references",
    "get_simple_property",
    "parse_name",
    "register_spec05_extractors",
    "register_spec06_extractors",
    "register_spec07_extractors",
    "register_spec08_extractors",
    "register_spec09_extractors",
    "scan_elements",
]
